version: '2' 
services:
  redis:
    image: redis
  headnode:
    image: lukasheinrich/recast-backend
    #try this in interactive session:
    #recast-directsub cap http://physics.nyu.edu/~lh1132/dummycomplex.zip complex_analysis/fullworkflow.yml /recastdata/outhere --track
    command: bash
    stdin_open: true
    tty: true
    environment:
      - CELERY_REDIS_HOST=redis
      - CELERY_REDIS_PORT=6379
      - CELERY_REDIS_DB=0
    volumes:
      - recastdata:/recastdata
  plugin:
    image: lukasheinrich/recast-cap-demo
    command: bash -c 'ssh-keyscan -t rsa shiptarget >> ~/.ssh/known_hosts ;cd /workdirsdata; celery worker -A recastbackend.fromenvapp:app -l debug -Q recast_cap_queue --logfile celery.log'
    # command: bash
    # stdin_open: true
    # tty: true
    environment:
      - C_FORCE_ROOT=yes
      - CELERY_REDIS_HOST=redis
      - CELERY_REDIS_PORT=6379
      - CELERY_REDIS_DB=0
      - RECAST_SHIP_USER=root
      - RECAST_SHIP_HOST=shiptarget
      - RECAST_SHIP_PORT=22
      - DOCKER_HOST=$DOCKER_HOST
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs
      - RECAST_IN_DOCKER_WORKDIRS_VOL=$RECAST_IN_DOCKER_WORKDIRS_VOL
    volumes:
      - recastdata:/recastdata
      - workdirsdata:/workdirsdata
      - ./dummyssh/id_rsa:/root/.ssh/id_rsa
      - $DOCKER_CERT_PATH:/certs 
  shiptarget:
    image: quay.io/macropin/sshd
    command: bash -c 'cat pubkey > /root/.ssh/authorized_keys; /usr/sbin/sshd -D -f /etc/ssh/sshd_config'
    volumes:
      - recastdata:/recastdata
      - ./dummyssh/id_rsa.pub:/pubkey:rw
volumes:
  recastdata:
    driver: local
  workdirsdata:
    external: true