version: '2' 
services:
  redis:
    image: redis
  headnode:
    image: lukasheinrich/recast-backend
    # command: recast-localsub http://physics.nyu.edu/~lh1132/michal.zip EwkTwoLepton recast_cap_queue test_zara_out --track
    command: bash
    stdin_open: true
    tty: true
    environment:
      - CELERY_REDIS_HOST=redis
      - CELERY_REDIS_PORT=6379
      - CELERY_REDIS_DB=0
    volumes:
      - recastdata:/recastdata
  plugin:
    image: lukasheinrich/recast-cap-demo
    command: bash -c 'cd /workdirsdata; celery worker -A recastbackend.fromenvapp:app -l debug -Q recast_cap_queue --logfile celery.log'
    # command: bash
    # stdin_open: true
    # tty: true
    environment:
      - C_FORCE_ROOT=yes
      - CELERY_REDIS_HOST=redis
      - CELERY_REDIS_PORT=6379
      - CELERY_REDIS_DB=0
      - RECAST_SHIP_USER=root
      - RECAST_SHIP_HOST=shiptarget
      - RECAST_SHIP_PORT=22
      - DOCKER_HOST=$DOCKER_HOST
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs
      - RECAST_CAP_IN_DOCKER_WORKDIR_VOL=/mnt/sda1/var/lib/docker/volumes/misc_workdirsdata/_data
    volumes:
      - recastdata:/recastdata
      - workdirsdata:/workdirsdata
      - ./id_rsa:/root/.ssh/id_rsa
      - $DOCKER_CERT_PATH:/certs 
  shiptarget:
    image: quay.io/macropin/sshd
    command: bash -c 'cp /keys/mykeys.pub /root/.ssh/authorized_keys; /usr/sbin/sshd -D -f /etc/ssh/sshd_config'
    volumes:
      - recastdata:/recastdata
      - ./id_rsa.pub:/keys/mykeys.pub:rw
volumes:
  recastdata:
    driver: local
  workdirsdata:
    driver: local