capbackend_config:
  results:
      - workflow: 'from-github/pseudocap:ewk_analyses/ewkdilepton_analysis/ewk_dilepton_recast_workflow.yml'
        results:
          - 'histfitprepare/out.yield'
          - 'histfitprepare/out.root'
          - 'fit/fit.tgz'
          - 'postproc/results.yaml'
        recastresult:
          adapter: recastbackend.recastadapters:pMSSMFormat_BestSR
          yamlfilepath: results.yaml
      - workflow: 'from-github/phenochain:madgraph_delphes.yml'
        results:
          - 'pythia/output.hepmc'
          - 'delphes/output.lhco'
          - 'delphes/output.root'
        recastresult:
          adapter: recastbackend.recastadapters:null_result
      - workflow: 'from-github/higgsmcproduction:rootflow-combined.yml'
        results:
          - 'rootmerge/anamerged.root'
          - 'grid/grid.tar.gz'
        recastresult:
          adapter: recastbackend.recastadapters:null_result
      - workflow: 'from-github/phenochain:madgraph_delphes_athena.yml'
        results:
          - 'pythia/output.hepmc'
          - 'delphes/output.lhco'
          - 'delphes/output.root'
          - 'athena/plot.png'
        recastresult:
          adapter: recastbackend.recastadapters:null_result
      - workflow: 'from-github/trivial_recast:rootflow.yml'
        results:
          - 'recast/recast.json'
        recastresult:
          adapter: recastbackend.recastadapters:standard_result
          jsonfilepath: 'recast.json'
  recast_workflow_config:
    - analysis_id: 1
      toplevel: from-github/trivial_recast
      workflow: rootflow.yml
    - analysis_id: 3
      toplevel: from-github/pseudocap
      workflow: ewk_analyses/ewkdilepton_analysis/ewk_dilepton_recast_workflow.yml
