plugin_configs:
  yadageworkflow:
      results:
        - workflow: 'from-github/trivial_recast:rootflow.yml'
          results:
            - 'recast/recast.json'
          recastresult:
            adapter: recastbackend.recastadapters:standard_result
            jsonfilepath: 'recast.json'
        - workflow: from-github/phenochain/checkmate_workflow:workflow.yml
          results:
            - 'format_results/limits.json'
          recastresult:
            adapter: recastbackend.recastadapters:standard_result
            jsonfilepath: 'limits.json'
            force_float: true
        - workflow: 'from-github/pseudocap:ewk_analyses/ewkdilepton_analysis/ewk_dilepton_recast_workflow.yml'
          results:
            - 'histfitprepare/out.yield'
            - 'histfitprepare/out.root'
            - 'fit/fit.tgz'
            - 'postproc/results.yaml'
          recastresult:
            adapter: recastbackend.recastadapters:pMSSMFormat_BestSR
            yamlfilepath: results.yaml
recast_wflowconfigs:
  - scanid: 1
    configname: 'atlas_ewksusy_2l'
    wflowplugin: yadageworkflow
    config:
      toplevel: from-github/pseudocap
      workflow: ewk_analyses/ewkdilepton_analysis/ewk_dilepton_recast_workflow.yml
  - scanid: 2
    configname: 'atlas_ewksusy_2l'
    wflowplugin: yadageworkflow
    config:
      toplevel: from-github/pseudocap
      workflow: ewk_analyses/ewkdilepton_analysis/ewk_dilepton_recast_workflow.yml
  - scanid: 3
    configname: dummyconfig
    wflowplugin: yadageworkflow
    config:
      toplevel: from-github/trivial_recast
      workflow: rootflow.yml
  - scanid: 4
    configname: stopcheckmate
    wflowplugin: yadageworkflow
    config:
      toplevel: from-github/phenochain/checkmate_workflow
      workflow: workflow.yml
      preset_pars:
        analysis: atlas_conf_2013_047
